### ISSUE TITLE
Add the Spanish used to generate the Aragonese and Aranese dev sets to the FLORES+.zip

### ISSUE THREAD

**Issue by zolastro** [transducens/PILAR#1]
Hi!

I assume you've used the resource available at [FLORES+](https://github.com/openlanguagedata/flores). However, since this resource might change in the future, I highly recommend including it within the zip file for easier tracking.

Cheers!

**Comment by aarongaliano** [comment]
Hi!

Yes, we have been using the FLORES+ development set. You are right that this may change in the future, so thanks for the suggestion to add it to our repository.
We have already included it in the zip file.

Cheers!
